### ISSUE TITLE
Fails when /hooks returns 404

### ISSUE THREAD

**Issue by markstos** [itchyny/github-migrator#3]
For some reason this returns 404:

https://api.github.com/repos/bergie/passport-saml/hooks?

The URL is correct, but either there are no hooks or my API token doesn't have permission to see them so the URL is 404.

Either way, `github-migrator` crashes at this point.

Instead, it should treat the case the same as "no hooks" and proceed from there.

I think this is really a bug in the Github API design, though. Returning "403 Forbidden" in this case seems more appropriate, or "204 No Content".

Thanks!

**Comment by markstos** [comment]
Here's an example of what the failure looks like:

```
<=== 404 Not Found: GET: https://api.github.com/repos/bergie/passport-saml/hooks?per_page=100
github-migrator: ListHooks bergie/passport-saml: Not Found
exit status 1
```
I don't recommend testing this bug live on the `bergie/passport-saml` website though-- it will take about an hour of importing time before it gets far enough to trigger this issue!

**Comment by itchyny** [comment]
I fixed this now, thanks.

**Comment by markstos** [comment]
That worked-- our import is complete now.

You were a big help-- どうもありがとう!
